// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrzV0PWZOMjdjHtt5tDLwlNK9dVxNnSzE',
    appId: '1:367737297835:web:4d673c680211f2dade10ee',
    messagingSenderId: '367737297835',
    projectId: 'flutter-firebase-netec',
    authDomain: 'flutter-firebase-netec.firebaseapp.com',
    storageBucket: 'flutter-firebase-netec.appspot.com',
    measurementId: 'G-J30WBE6Z0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbaD_UYLWuZWd4vLV13aHQKITkovikqrE',
    appId: '1:367737297835:android:8abf6555fab7e664de10ee',
    messagingSenderId: '367737297835',
    projectId: 'flutter-firebase-netec',
    storageBucket: 'flutter-firebase-netec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDao1bBmgQMWEeC_Mjo2tf84tHuN-NX-fA',
    appId: '1:367737297835:ios:58e197274a0ab82bde10ee',
    messagingSenderId: '367737297835',
    projectId: 'flutter-firebase-netec',
    storageBucket: 'flutter-firebase-netec.appspot.com',
    iosBundleId: 'com.practicas.flutter.authFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDao1bBmgQMWEeC_Mjo2tf84tHuN-NX-fA',
    appId: '1:367737297835:ios:58e197274a0ab82bde10ee',
    messagingSenderId: '367737297835',
    projectId: 'flutter-firebase-netec',
    storageBucket: 'flutter-firebase-netec.appspot.com',
    iosBundleId: 'com.practicas.flutter.authFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrzV0PWZOMjdjHtt5tDLwlNK9dVxNnSzE',
    appId: '1:367737297835:web:7fd580f16ed7e41cde10ee',
    messagingSenderId: '367737297835',
    projectId: 'flutter-firebase-netec',
    authDomain: 'flutter-firebase-netec.firebaseapp.com',
    storageBucket: 'flutter-firebase-netec.appspot.com',
    measurementId: 'G-10CLKE3C8Q',
  );
}
